/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package presentacion;

import java.awt.Color;

/**
 *
 * @author IVAN
 */
public class FrmMenu extends javax.swing.JFrame {

    /**
     * Creates new form FrmMenu
     */
    public FrmMenu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
<<<<<<< HEAD
        btnEliminarActivo = new javax.swing.JButton();
=======
<<<<<<< Updated upstream
        btnRegistrarActivo = new javax.swing.JButton();
>>>>>>> Seleccionar-activo-para-mantenimiento
        jLabel1 = new javax.swing.JLabel();
=======
        btnEliminarActivo = new javax.swing.JButton();
>>>>>>> Stashed changes
        btnConsultarActivo = new javax.swing.JButton();
        btnModificarActivo = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnConsultarActivo1 = new javax.swing.JButton();
<<<<<<< HEAD
        btnRegistrarActivo1 = new javax.swing.JButton();
        btnEliminarActivo1 = new javax.swing.JButton();
=======
<<<<<<< Updated upstream
=======
        btnRegistrarActivo1 = new javax.swing.JButton();
        btnEliminarActivo1 = new javax.swing.JButton();
        btnConsultarMantenimiento = new javax.swing.JButton();
        btnMantenimientoActivo = new javax.swing.JButton();
>>>>>>> Stashed changes
>>>>>>> Seleccionar-activo-para-mantenimiento

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnEliminarActivo.setBackground(new java.awt.Color(0, 153, 204));
        btnEliminarActivo.setFont(new java.awt.Font("Roboto Light", 1, 14)); // NOI18N
        btnEliminarActivo.setForeground(new java.awt.Color(255, 255, 255));
        btnEliminarActivo.setText("Asignar Activo");
        btnEliminarActivo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnEliminarActivoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnEliminarActivoMouseExited(evt);
            }
        });
        btnEliminarActivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActivoActionPerformed(evt);
            }
        });
        jPanel1.add(btnEliminarActivo, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 260, 290, -1));

        btnConsultarActivo.setBackground(new java.awt.Color(0, 153, 204));
        btnConsultarActivo.setFont(new java.awt.Font("Roboto Light", 1, 14)); // NOI18N
        btnConsultarActivo.setForeground(new java.awt.Color(255, 255, 255));
        btnConsultarActivo.setText("Ver asignaciones del activo");
        btnConsultarActivo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnConsultarActivoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnConsultarActivoMouseExited(evt);
            }
        });
        btnConsultarActivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultarActivoActionPerformed(evt);
            }
        });
<<<<<<< HEAD
        jPanel1.add(btnConsultarActivo, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 350, 290, -1));
=======
<<<<<<< Updated upstream
        jPanel1.add(btnConsultarActivo, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 290, 290, -1));
=======
        jPanel1.add(btnConsultarActivo, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 340, 290, -1));
>>>>>>> Stashed changes
>>>>>>> Seleccionar-activo-para-mantenimiento

        btnModificarActivo.setBackground(new java.awt.Color(0, 153, 204));
        btnModificarActivo.setFont(new java.awt.Font("Roboto Light", 1, 14)); // NOI18N
        btnModificarActivo.setForeground(new java.awt.Color(255, 255, 255));
        btnModificarActivo.setText("Modificar Activo");
        btnModificarActivo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnModificarActivoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnModificarActivoMouseExited(evt);
            }
        });
        btnModificarActivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarActivoActionPerformed(evt);
            }
        });
        jPanel1.add(btnModificarActivo, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 180, 290, -1));

        jPanel2.setBackground(new java.awt.Color(0, 153, 255));
        jPanel2.setForeground(new java.awt.Color(0, 153, 255));

        jLabel1.setFont(new java.awt.Font("Roboto Medium", 1, 36)); // NOI18N
        jLabel1.setText("Administrar Activos");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel1)
                .addContainerGap(29, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel1)
                .addContainerGap(41, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 0, 420, -1));

        btnConsultarActivo1.setBackground(new java.awt.Color(0, 153, 204));
        btnConsultarActivo1.setFont(new java.awt.Font("Roboto Light", 1, 14)); // NOI18N
        btnConsultarActivo1.setForeground(new java.awt.Color(255, 255, 255));
        btnConsultarActivo1.setText("Consultar estado del Activo");
        btnConsultarActivo1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultarActivo1ActionPerformed(evt);
            }
        });
<<<<<<< HEAD
        jPanel1.add(btnConsultarActivo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 310, 290, -1));
=======
<<<<<<< Updated upstream
        jPanel1.add(btnConsultarActivo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 240, 290, -1));
=======
        jPanel1.add(btnConsultarActivo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 300, 290, -1));
>>>>>>> Seleccionar-activo-para-mantenimiento

        btnRegistrarActivo1.setBackground(new java.awt.Color(0, 153, 204));
        btnRegistrarActivo1.setFont(new java.awt.Font("Roboto Light", 1, 14)); // NOI18N
        btnRegistrarActivo1.setForeground(new java.awt.Color(255, 255, 255));
        btnRegistrarActivo1.setText("Registrar Activo");
        btnRegistrarActivo1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnRegistrarActivo1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnRegistrarActivo1MouseExited(evt);
            }
        });
        btnRegistrarActivo1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarActivo1ActionPerformed(evt);
            }
        });
        jPanel1.add(btnRegistrarActivo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 140, 290, -1));

        btnEliminarActivo1.setBackground(new java.awt.Color(0, 153, 204));
        btnEliminarActivo1.setFont(new java.awt.Font("Roboto Light", 1, 14)); // NOI18N
        btnEliminarActivo1.setForeground(new java.awt.Color(255, 255, 255));
        btnEliminarActivo1.setText("Eliminar Activo");
        btnEliminarActivo1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnEliminarActivo1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnEliminarActivo1MouseExited(evt);
            }
        });
        btnEliminarActivo1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActivo1ActionPerformed(evt);
            }
        });
        jPanel1.add(btnEliminarActivo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 220, 290, -1));
<<<<<<< HEAD
=======
>>>>>>> Stashed changes

        btnConsultarMantenimiento.setBackground(new java.awt.Color(0, 153, 204));
        btnConsultarMantenimiento.setFont(new java.awt.Font("Roboto Light", 1, 14)); // NOI18N
        btnConsultarMantenimiento.setForeground(new java.awt.Color(255, 255, 255));
        btnConsultarMantenimiento.setText("Consultar Mantenimientos");
        btnConsultarMantenimiento.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnConsultarMantenimientoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnConsultarMantenimientoMouseExited(evt);
            }
        });
        btnConsultarMantenimiento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultarMantenimientoActionPerformed(evt);
            }
        });
        jPanel1.add(btnConsultarMantenimiento, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 420, 290, -1));

        btnMantenimientoActivo.setBackground(new java.awt.Color(0, 153, 204));
        btnMantenimientoActivo.setFont(new java.awt.Font("Roboto Light", 1, 14)); // NOI18N
        btnMantenimientoActivo.setForeground(new java.awt.Color(255, 255, 255));
        btnMantenimientoActivo.setText("Programar Mantenimiento");
        btnMantenimientoActivo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnMantenimientoActivoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnMantenimientoActivoMouseExited(evt);
            }
        });
        btnMantenimientoActivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMantenimientoActivoActionPerformed(evt);
            }
        });
        jPanel1.add(btnMantenimientoActivo, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 380, 290, -1));
>>>>>>> Seleccionar-activo-para-mantenimiento

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 389, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
<<<<<<< HEAD
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 414, Short.MAX_VALUE)
=======
<<<<<<< Updated upstream
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 343, Short.MAX_VALUE)
=======
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 460, Short.MAX_VALUE)
>>>>>>> Stashed changes
>>>>>>> Seleccionar-activo-para-mantenimiento
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnEliminarActivoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEliminarActivoMouseEntered
        btnEliminarActivo.setBackground(new Color(0, 156, 223));
    }//GEN-LAST:event_btnEliminarActivoMouseEntered

    private void btnEliminarActivoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEliminarActivoMouseExited
        btnEliminarActivo.setBackground(new Color(0, 134, 190));
    }//GEN-LAST:event_btnEliminarActivoMouseExited

    private void btnEliminarActivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActivoActionPerformed

        FrmBuscarActivo frmBuscarActivos = new FrmBuscarActivo();
        dispose();
        frmBuscarActivos.setVisible(true);

    }//GEN-LAST:event_btnEliminarActivoActionPerformed

    private void btnConsultarActivoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnConsultarActivoMouseEntered
        btnConsultarActivo.setBackground(new Color(0, 156, 223));
    }//GEN-LAST:event_btnConsultarActivoMouseEntered

    private void btnConsultarActivoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnConsultarActivoMouseExited
        btnConsultarActivo.setBackground(new Color(0, 134, 190));
    }//GEN-LAST:event_btnConsultarActivoMouseExited

    private void btnConsultarActivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultarActivoActionPerformed
        FrmConsultarAsignado frmVerificarAsignado = new FrmConsultarAsignado();
        dispose();
        frmVerificarAsignado.setVisible(true);
    }//GEN-LAST:event_btnConsultarActivoActionPerformed

    private void btnModificarActivoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnModificarActivoMouseEntered
        btnModificarActivo.setBackground(new Color(0, 156, 223));
    }//GEN-LAST:event_btnModificarActivoMouseEntered

    private void btnModificarActivoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnModificarActivoMouseExited
        btnModificarActivo.setBackground(new Color(0, 134, 190));
    }//GEN-LAST:event_btnModificarActivoMouseExited

    private void btnModificarActivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarActivoActionPerformed
       FrmModificarActivo frmModificarActivo = new FrmModificarActivo();
       dispose();
       frmModificarActivo.setVisible(true);
    }//GEN-LAST:event_btnModificarActivoActionPerformed

    private void btnConsultarActivo1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultarActivo1ActionPerformed
        FrmConsultarEstado frmVerificarEstado = new FrmConsultarEstado();
        dispose();
        frmVerificarEstado.setVisible(true);
    }//GEN-LAST:event_btnConsultarActivo1ActionPerformed

<<<<<<< HEAD
=======
<<<<<<< Updated upstream
=======
>>>>>>> Seleccionar-activo-para-mantenimiento
    private void btnRegistrarActivo1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRegistrarActivo1MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_btnRegistrarActivo1MouseEntered

    private void btnRegistrarActivo1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRegistrarActivo1MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_btnRegistrarActivo1MouseExited

    private void btnRegistrarActivo1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarActivo1ActionPerformed
      FrmMenuControlarRegistro frmRegistrarActivos = new FrmMenuControlarRegistro();
        dispose();
        frmRegistrarActivos.setVisible(true);
    }//GEN-LAST:event_btnRegistrarActivo1ActionPerformed

    private void btnEliminarActivo1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEliminarActivo1MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_btnEliminarActivo1MouseEntered

    private void btnEliminarActivo1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEliminarActivo1MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_btnEliminarActivo1MouseExited

    private void btnEliminarActivo1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActivo1ActionPerformed
      FrmEliminarActivo frmEliminarActivos = new FrmEliminarActivo();
        dispose();
        frmEliminarActivos.setVisible(true);
    }//GEN-LAST:event_btnEliminarActivo1ActionPerformed

<<<<<<< HEAD
=======
    private void btnConsultarMantenimientoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnConsultarMantenimientoMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_btnConsultarMantenimientoMouseEntered

    private void btnConsultarMantenimientoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnConsultarMantenimientoMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_btnConsultarMantenimientoMouseExited

    private void btnConsultarMantenimientoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultarMantenimientoActionPerformed
        FrmConsultarMantenimientos frmConsultarMantenimientos = new FrmConsultarMantenimientos();
        dispose();
        frmConsultarMantenimientos.setVisible(true);
    }//GEN-LAST:event_btnConsultarMantenimientoActionPerformed

    private void btnMantenimientoActivoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMantenimientoActivoMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_btnMantenimientoActivoMouseEntered

    private void btnMantenimientoActivoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMantenimientoActivoMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_btnMantenimientoActivoMouseExited

    private void btnMantenimientoActivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMantenimientoActivoActionPerformed
        FrmProgramarMantenimiento frmProgramarMantenimiento = new FrmProgramarMantenimiento();
        dispose();
        frmProgramarMantenimiento.setVisible(true);
    }//GEN-LAST:event_btnMantenimientoActivoActionPerformed

>>>>>>> Stashed changes
>>>>>>> Seleccionar-activo-para-mantenimiento
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnConsultarActivo;
    private javax.swing.JButton btnConsultarActivo1;
<<<<<<< HEAD
    private javax.swing.JButton btnEliminarActivo;
    private javax.swing.JButton btnEliminarActivo1;
=======
<<<<<<< Updated upstream
=======
    private javax.swing.JButton btnConsultarMantenimiento;
    private javax.swing.JButton btnEliminarActivo;
    private javax.swing.JButton btnEliminarActivo1;
    private javax.swing.JButton btnMantenimientoActivo;
>>>>>>> Stashed changes
>>>>>>> Seleccionar-activo-para-mantenimiento
    private javax.swing.JButton btnModificarActivo;
    private javax.swing.JButton btnRegistrarActivo1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
